cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'openssl'
brew 'node'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'
brew 'wget'
brew 'node'
brew 'gpg'
brew 'hub'
brew 'fzf'
brew 'yarn'
brew 'go'
brew 'hg'
brew 'nodenv'
brew 'node-build'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'steam'
cask 'vlc'
cask 'imageoptim'
cask 'transmission'
cask 'iterm2'
cask 'dropbox'
cask 'adobe-creative-cloud'
cask 'spotify'
cask 'fontexplorer-x-pro'
