# Install cask
install caskroom/cask/brew-cask

# Install cask apps
cask install dropbox
cask install google-drive
cask install google-chrome
cask install iterm2
cask install atom
cask install hipchat
cask install dashlane
cask install spotify
cask install vlc
cask install utorrent
cask install adobe-creative-cloud

# Install other apps
install hub
install rbenv
install rbenv-gem-rehash
install ruby-build
install mongodb
install redis
install elasticsearch
install gpg
install node
